//
//  OAQuickAction.h
//  OsmAnd
//
//  Created by Paul on 8/6/19.
//  Copyright © 2019 OsmAnd. All rights reserved.
//

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, EOAQuickActionType)
{
    EOAQuickActionTypeNew = 1,
    EOAQuickActionTypeMarker,
    EOAQuickActionTypeFavorite,
    EOAQuickActionTypeShowFavorite,
    EOAQuickActionTypeTogglePOI,
    EOAQuickActionTypeGPX,
    EOAQuickActionTypeParking,
    EOAQuickActionTypeTakeAudioNote,
    EOAQuickActionTypeTakeVideoNote,
    EOAQuickActionTypeTakePhoto,
    EOAQuickActionTypeNavVoice,
    EOAQuickActionTypeAddNote,
    EOAQuickActionTypeAddPOI,
    EOAQuickActionTypeMapStyle,
    EOAQuickActionTypeMapOverlay,
    EOAQuickActionTypeMapUnderlay,
    EOAQuickActionTypeMapSource,
    EOAQuickActionTypeAddDestination,
    EOAQuickActionTypeReplaceDestination,
    EOAQuickActionTypeAddFirstIntermediate,
    EOAQuickActionTypeAutoZoomMap,
    EOAQuickActionTypeToggleOsmNotes,
    EOAQuickActionTypeToggleNavigation,
    EOAQuickActionTypeResumePauseNavigation,
    EOAQuickActionTypeToggleDayNight,
    EOAQuickActionTypeToggleGPX
};

@interface OAQuickAction : NSObject

@property (nonatomic) EOAQuickActionType type;
@property (nonatomic) long identifier;
@property (nonatomic) NSString *name;
@property (nonatomic) NSDictionary<NSString *, NSString *> *params;

- (instancetype) initWithType:(NSInteger)type nameRes:(NSInteger)nameRes;
- (instancetype) initWithType:(NSInteger)type;
- (instancetype) initWithAction:(OAQuickAction *)action;

-(NSInteger) getNameRes;
-(NSString *) getIconResName;

-(long) getId;
-(EOAQuickActionType)getType;
-(BOOL) isActionEditable;
-(NSString *) getName;

-(NSDictionary <NSString *, NSString *> *) getParams;
-(void) setName:(NSString *) name;
-(void) setParams:(NSDictionary<NSString *, NSString *> *) params;
-(BOOL) isActionWithSlash;
-(NSString *) getActionText;

//public void setAutoGeneratedTitle(EditText title){
//}

-(void) execute;
-(void) drawUI;
-(BOOL) fillParams;

-(BOOL) hasInstanceInList:(NSArray<OAQuickAction *> *)active;

@end
