//
//  OAQuickAction.m
//  OsmAnd
//
//  Created by Paul on 8/6/19.
//  Copyright © 2019 OsmAnd. All rights reserved.
//

#import "OAQuickAction.h"

@implementation OAQuickAction
{
    NSInteger _nameRes;
    NSString *_iconResName;
    BOOL _isActionEditable;
}

- (instancetype) init
{
    self = [super init];
    if (self) {
        _identifier = [[NSDate date] timeIntervalSince1970] * 1000;
    }
    return self;
}

-(instancetype) initWithType:(NSInteger)type nameRes:(NSInteger)nameRes
{
    self = [super init];
    if (self) {
        _identifier = [[NSDate date] timeIntervalSince1970] * 1000;
        _nameRes = nameRes;
        _type = type;
    }
    return self;
}

- (instancetype) initWithType:(NSInteger)type
{
    self = [super init];
    if (self) {
        _identifier = [[NSDate date] timeIntervalSince1970] * 1000;
        _type = type;
//        _nameRes = QuickActionFactory.getActionName(type);
//        _iconRes = QuickActionFactory.getActionIcon(type);
//        _isActionEditable = QuickActionFactory.isActionEditable(type);
    }
    return self;
}

- (instancetype) initWithAction:(OAQuickAction *)action
{
    self = [super init];
    if (self) {
        _identifier = action.identifier;
        _name = action.getName;
        _type = action.type;
        _params = action.getParams;
        
//        this.nameRes = QuickActionFactory.getActionName(type);
//        this.iconRes = QuickActionFactory.getActionIcon(type);
//        this.isActionEditable = QuickActionFactory.isActionEditable(type);
    }
    return self;
}

-(NSInteger) getNameRes
{
    return _nameRes;
}

-(NSString *) getIconResName
{
    return _iconResName;
}

-(long) getId
{
    return _identifier;
}

-(EOAQuickActionType) getType
{
    return _type;
}

-(BOOL) isActionEditable
{
    return _isActionEditable;
}

-(NSString *) getName
{
    return _name == nil ? @"" : _name;
}

-(NSDictionary<NSString *, NSString *> *) getParams
{
    if (!_params)
        _params = [NSDictionary new];

    return _params;
}

-(void) setName:(NSString *) name
{
    _name = name;
}

-(void) setParams:(NSDictionary<NSString *, NSString *> *) params
{
    _params = params;
}

-(BOOL) isActionWithSlash
{
    return NO;
}

// TODO clear?
-(NSString *) getActionText
{
    return _name;
}

//public void setAutoGeneratedTitle(EditText title){
//}

- (void)execute
{
}

- (void)drawUI
{
}

- (BOOL)fillParams
{
    return YES;
}

-(BOOL) hasInstanceInList:(NSArray<OAQuickAction *> *) active
{
    for (OAQuickAction *action in active)
    {
        if (action.type == _type)
            return YES;
    }

    return NO;
}

- (BOOL)isEqual:(id)object
{
    if (self == object)
        return YES;
    if (!object)
        return NO;
    
    if ([object isKindOfClass:self.class])
    {
        OAQuickAction *action = (OAQuickAction *) object;
        if (_type != action.type)
            return NO;
        if (_identifier != action.identifier)
            return NO;
        return YES;
    }
    else
    {
        return NO;
    }
}

- (NSUInteger)hash
{
    NSInteger result = _type;
    result = 31 * result + (NSInteger) (_identifier ^ (_identifier >> 32));
    result = 31 * result + _nameRes;
    result = 31 * result + [_iconResName hash];
    result = 31 * result + (_name != nil ? [_name hash] : 0);
    return result;
}

@end
